CREATE TABLE USER_DETAILS (
 ID INTEGER PRIMARY KEY,
 FIRST_NAME VARCHAR(50) NOT NULL,
 LAST_NAME VARCHAR(50) NOT NULL,
 ACTIVE BOOLEAN,
 CREATED_AT TIMESTAMP,
 CREATED_BY VARCHAR(50),
 UPDATED_AT TIMESTAMP,
 UPDATED_BY VARCHAR(50),
 VERSION INTEGER,
 FLAG BOOLEAN
 );
